version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq/
        - rabbitmq-logs:/var/log/rabbitmq/

volumes:
  rabbitmq-data:
  rabbitmq-logs: