version: "3"

services:
  rabbitmq:
    volumes:
      - ./container_fixtures/rabbitmq/certs/ca_certificate.pem:/etc/ssl/certs/ca_certificate.pem
      - ./container_fixtures/rabbitmq/certs/server_rabbit.trento.local_key.pem:/var/lib/rabbitmq/server_rabbit.trento.local_key.pem
      - ./container_fixtures/rabbitmq/certs/server_rabbit.trento.local_certificate.pem:/var/lib/rabbitmq/server_rabbit.trento.local_certificate.pem
      - ./container_fixtures/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    image: rabbitmq:3.12.6-management-alpine
    ports:
      - 5677:5671
      - 5675:5672
      - 15673:15672
volumes:
  rabbitmq-data:
  rabbitmq-logs: