ifndef::site-gen-antora[:relfileprefix: docs/]
:ci-url: https://github.com/trento-project/agent/actions/workflows/ci.yaml
:ci-badge: https://github.com/trento-project/agent/actions/workflows/ci.yaml/badge.svg
:coveralls-url: https://coveralls.io/github/trento-project/agent?branch=main
:coveralls-badge: https://coveralls.io/repos/github/trento-project/agent/badge.svg?branch=main

[[trento_agent]]
= Trento Agent

link:{ci-url}[image:{ci-badge}[CI]]
link:{coveralls-url}[image:{coveralls-badge}[Coverage Status]]

The agents are the `+trento+` processes that run in each of the nodes of
a target HA SAP Applications cluster.

== Table of contents
* xref:#trento_agent[Trento Agent]
** xref:#features[Features]
 *** xref:#heartbeating[Heartbeating]
 *** xref:#discovery[Discovery]
** xref:#installation[Installation]
 *** xref:#requirements[Requirements]
 *** xref:#rpm_packages[RPM Packages]
 *** xref:#compile_from_source[Compile from source]
 *** xref:#installation_script[Installation Scripts]
** xref:#usage[Usage]
 *** xref:#starting_the_trento_agent_service[Starting Trento Agent service]
 *** xref:#manual_installation[Manually running Trento Agents]
*** xref:#configuration[Configuration]
 **** xref:#locations[Locations]
 **** xref:#examples[Examples]
*** xref:#environment-variables[Environment Variables]
** xref:#development[Development]
*** xref:#build_system[Build system]
*** xref:#development_dependencies[Development dependencies]
*** xref:#fake_agent_id[Fake Agent ID] 
*** xref:#fact_gathering_plugin_system[Fact gathering plugin system]
*** xref:#sapcontrol_web_service[SAPControl web service] 
** xref:#support[Support]
** xref:#contributing[Contributing]
** xref:#license[License]

[[features]]
== Features

Agents provide two main functionalities:

* Heartbeating
* Discovery

[[heartbeating]]
=== Heartbeating

When Trento agent starts, it begins notifying the control plane about
its presence in the cluster by _heartbeating_ periodically.

[[discovery]]
=== Discovery

Agents are responsible for the _discovery_ of all the clustered
components that are required in order to run highly available SAP
Applications.

Discoveries gather information about these aspects of a target host

* OSVersion, HostName, HostIpAddresses… - _HostDiscovery_
* Cloud Service Provider it is running on - _CloudDiscovery_
* Pacemaker/Corosync/SBD metadata - _ClusterDiscovery_
* SAP components running on it (Application instances, Database
instances) - _SAPSystemsDiscovery_
* SLES Subscriptions - _SubscriptionDiscovery_

[[installation]]
== Installation

[[requirements]]
=== Requirements

_Trento Agent_ needs to interact with a number of low-level system
components which are part of the
https://www.suse.com/products/sles-for-sap/[SUSE Linux Enterprise Server
for SAP Applications] Linux distribution.

These could in theory also be installed and configured on other
distributions providing the same functionalities, but this use case is
not within the scope of the active development.

In addition to that, _Trento Agent_ can also optionally integrate with
the https://github.com/prometheus/node_exporter[Prometheus node_exporter
component] to collect host information for the monitoring functionality.

The resource footprint of _Trento Agent_ should not impact the
performance of the host it runs on.

[[rpm_packages]]
==== RPM Packages

RPM packages for _SUSE Linux Enterprise Server for SAP Applications_ can
be installed using the `+zypper+` package manager:

[source,shell]
----
zypper in -y trento-agent
----

Continuously rebuilt development packages are also available via the
Open Build Service (OBS):

* https://software.opensuse.org//download.html?project=devel%3Asap%3Atrento%3Afactory&package=trento-agent[Factory
(rolling version)]
* https://software.opensuse.org//download.html?project=devel%3Asap%3Atrento&package=trento-agent[Latest
stable]

[[compile_from_source]]
==== Compile from source

You can also clone this repo and build sources manually:

[source,shell]
----
git clone https://github.com/trento-project/agent.git
cd agent
make build
----

See the section below to know more about the build dependencies.
[[installation_script]]
==== Installation Script

A little installation script is provided to automatically install and
update the development build of Trento Agent.

Please follow the instructions in the given order.

You can `+curl | bash+` it if you want to live on the edge:
[source,shell]
....
curl -sfL https://raw.githubusercontent.com/trento-project/agent/main/install-agent.sh | sudo bash
....

or you can fetch the script, and then execute it manually:
[source,shell]
....
curl -O https://raw.githubusercontent.com/trento-project/agent/main/install-agent.sh
chmod 700 install-agent.sh
sudo ./install-agent.sh
....

The script will ask you for some input.

* `+server-ip+`: the address where Trento server can be reached.
* `+facts-service-url+`: the address of the AMQP service shared with
Wanda where fact gathering request are received.
* `+api-key+`: the API key generated by the server that allows agents to
actually communicate with the control plane

You can pass these arguments as flags or env variables too:
[source,shell]
....
curl -sfL https://raw.githubusercontent.com/trento-project/agent/main/install-agent.sh | sudo bash -s - --server-url=http://192.168.33.1
--facts-service-url=amqp://guest:guest@localhost:5672 --api-key <some-api-key>
....
[source,shell]
....
SERVER_IP=192.168.33.1 FACTS_SERVICE_URL=amqp://guest:guest@localhost:5672 API_KEY=<some-api-key> sudo ./install-agent.sh
....

[[usage]]
== Usage

[[starting_the_trento_agent_service]]
=== Starting the Trento Agent service

The installation script does not start the agent automatically.

You can enable boot startup and launch it with systemd:

....
sudo systemctl enable --now trento-agent
....

Please, make sure the server is running before starting the agent.

That’s it! You can now reach the Trento web UI and start using it.

[[manual_installation]]
=== Manually running Trento Agents

Trento Agents need to run in the same systems hosting the HA Cluster
services, so running them in isolated environments (e.g. serverless,
containers, etc.) makes little sense, as they won’t be able as the
discovery mechanisms will not be able to report any host information.

____
NOTE: Suggested installation instructions for SUSE-based distributions,
adjust accordingly
____

_Optionally_ install and start `+node_exporter+`:

[source,shell]
----
zypper in -y golang-github-prometheus-node_exporter
systemctl start prometheus-node_exporter
----

____
NOTE: The `+prometheus-node_exporter+` zypper package might or might not
be available depending on the SLES version.
____

To start the trento agent:

[source,shell]
----
./trento-agent start
----

Alternatively, you can use the `+trento-agent.service+` from this
repository and start it, which will start `+node_exporter+`
automatically as a dependency:

[source,shell]
----
cp packaging/systemd/trento-agent.service /etc/systemd/system
systemctl daemon-reload
systemctl start trento-agent.service
----

____
If the discovery loop is being executed too frequently, and this impacts
the Web interface performance, the agent has the option to configure the
discovery loop mechanism using the various
`+--<cloud,cluster,host,sapsystem>-discovery-period+` flags. Increasing
this value improves the overall performance of the application
____

[[configuration]]
=== Configuration

Trento Agent can be run with a config file in replacement of
command-line arguments.

[[locations]]
==== Locations

Configuration, if not otherwise specified by the
`+--config=/path/to/config.yaml+` option, would be searched in following
locations:

Note that order represents priority

* `+/etc/trento/agent.yaml+` <– first location looked
* `+/usr/etc/trento/agent.yaml+` <– fallback here if config not found in
previous location
* `+~/.config/trento/agent.yaml+` aka user’s home <– fallback here

`+yaml+` is the only supported format at the moment.

==== Examples
[source,shell]
....
# /etc/trento/agent.yaml

api-key: <api-key-generated-from-the-server>
server-ip: https://localhost
facts-service-url: amqp://guest:guest@localhost:5672
....

Please refer to the link:https://github.com/trento-project/agent/blob/main/packaging/config/agent.yaml[default
configuration file] for more detailed information on the various
settings.

[[environment_variables]]
=== Environment Variables

All of the options supported by the command line and configuration file
can be provided as environment variables as well.

The rule is: get the option name eg. `+api-key+`, replace dashes `+-+`
with underscores `+_+`, make it uppercase and add a `+TRENTO_+` prefix.

Examples:

`+api-key+` -> `+TRENTO_API_KEY=<some-api-key> ./trento-agent start+`

`+server-ip+` ->
`+TRENTO_SERVER_IP=https://localhost ./trento-agent start+`

[[development]]
== Development
[[build_system]]
=== Build system

We use GNU Make as a task manager; here are some common targets:

[source,shell]
----
make # clean, test and build everything

make build # build for the current architecture
make cross-compile # build for a list of supported architectures
make bundle # prepare all the bundles for each built artifact
make clean # removes any build artifact
make test # executes all the tests
make test-short # executes all tests that don't require dependencies
make test-build # executes tests on built artifacts
make fmt # fixes code formatting
make web-assets # invokes the frontend build scripts
make generate # refresh automatically generated code (e.g. static Go mocks)
----

Feel free to peek at the Makefile to know more.
[[development_dependencies]]
=== Development dependencies

Additionally, for the development we use
https://github.com/vektra/mockery[`+mockery+`] for the `+generate+`
target, which in turn is required for the `+test+` target. You can
install it with `+go install github.com/vektra/mockery/v2+`.

____
Be sure to add the `+mockery+` binary to your `+$PATH+` environment
variable so that `+make+` can find it. That usually comes with
configuring `+$GOPATH+`, `+$GOBIN+`, and adding the latter to your
`+$PATH+`.
____

____
Please note that the `+trento agent+` component requires to be running
on the OS (_not_ inside a container) so, while it is technically
possible to run `+trento agent+` commands in the container, it makes
little sense because most of its internals require direct access to the
host of the HA Cluster components.
____
[[fake_agent_id]]
=== Fake Agent ID

In some circumstances, having a fake Agent ID might be useful, especially
during development and testing stages. The hidden `+force-agent-id+`
flag is available for that.

Here an example on how to use it:

`+./trento-agent start --force-agent-id "800ddd9b-8497-493f-b9fa-1bd6c9afb230"+`

____
Don’t use this flag on production systems, as the agent ID must be
unique by definition and any change affects the whole Trento usage.
____
[[fact_gathering_plugin_system]]
=== Fact gathering plugin system

A plugin system is available in the Agent, in order to add new fact
gathering options, so it can run user created checks in the server side.

To create a new plugin (check the link:https://github.com/trento-project/agent/blob/main/plugin_examples/dummy/dummy.go[example]
dummy plugin for that) follow the next steps:

* Create a new Golang package. This is as simple as creating a new
folder (it can be created anywhere, it doesn’t need to be in the Agent
code directory) with `+.go+` file inside. Name the Golang file with a
meaningful name (even though, it is not relevant for the usage itself).
* The `+.go+` file implements the `+main+` package and imports the
`+go-plugin+` package as seen in the example.
* Implement the gathering function with the
`+func (s exampleGatherer) Gather(ctx context.Context, factsRequests []gatherers.FactRequest) ([]gatherers.Fact, error)+`
signature. This function must gather the facts from the system where the
Agent is running.
* This function receives a list of fact gathering requests to gather,
which entirely depends on the gathering code nature.
* Copy the `+main()+` function from the
link:https://github.com/trento-project/agent/blob/main/plugin_examples/dummy/dummy.go[example] file. Simply replace the gatherer
struct name there.
* Once the plugin is implemented, it must be compiled. Use the next
command for that:
`+go build -o /usr/etc/trento/example ./your_plugin_folder/example.go+`.
The `+-o+` flag specifies the destination of the created binary, which
the Agent needs to load. This folder is the same specified in the
`+--plugins-folder+` flag in the Agent execution. In this case, the used
name for the output in the `+-o+` flag is relevant, as this name is the
gatherer name that must be used in the server side checks declaration.
* In order to see that the plugin is correctly loaded, run:
`+./trento-agent facts list+`.

Find the official gatherers code in:
link:https://github.com/trento-project/agent/tree/main/internal/factsengine/gatherers[gatherers directory].

____
*** By now, it only supports Golang based implementations, but this
could be extendable (if this requirement is needed, please open a Github
ticket with this feature request).
____
[[sapcontrol_web_service]]
=== SAPControl web service

The SAPControl web service soap client was generated by
https://github.com/hooklift/gowsdl[hooklift/gowsdl], then the methods
and structs needed were cherry-picked and adapted. For reference, you
can find the full, generated, web service code
link:https://github.com/trento-project/agent/blob/main/docs/_generated_soap_wsdl.go[here].
[[support]]
== Support

Please only report bugs via
https://github.com/trento-project/agent/issues[GitHub issues]; for any
other inquiry or topic use
https://github.com/trento-project/agent/discussions[GitHub discussion].
[[contributing]]
== Contributing

See xref:CONTRIBUTING.adoc[CONTRIBUTING]

[[license]]
== License

See the link:https://github.com/trento-project/agent/blob/main/LICENSE[License] notice.