// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v22dbus "github.com/coreos/go-systemd/v22/dbus"
)

// MockConnector is an autogenerated mock type for the Connector type
type MockConnector struct {
	mock.Mock
}

type MockConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnector) EXPECT() *MockConnector_Expecter {
	return &MockConnector_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockConnector) Close() {
	_m.Called()
}

// MockConnector_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockConnector_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockConnector_Expecter) Close() *MockConnector_Close_Call {
	return &MockConnector_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockConnector_Close_Call) Run(run func()) *MockConnector_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnector_Close_Call) Return() *MockConnector_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnector_Close_Call) RunAndReturn(run func()) *MockConnector_Close_Call {
	_c.Run(run)
	return _c
}

// DisableUnitFilesContext provides a mock function with given fields: ctx, files, runtime
func (_m *MockConnector) DisableUnitFilesContext(ctx context.Context, files []string, runtime bool) ([]v22dbus.DisableUnitFileChange, error) {
	ret := _m.Called(ctx, files, runtime)

	if len(ret) == 0 {
		panic("no return value specified for DisableUnitFilesContext")
	}

	var r0 []v22dbus.DisableUnitFileChange
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, bool) ([]v22dbus.DisableUnitFileChange, error)); ok {
		return rf(ctx, files, runtime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, bool) []v22dbus.DisableUnitFileChange); ok {
		r0 = rf(ctx, files, runtime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v22dbus.DisableUnitFileChange)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, bool) error); ok {
		r1 = rf(ctx, files, runtime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnector_DisableUnitFilesContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableUnitFilesContext'
type MockConnector_DisableUnitFilesContext_Call struct {
	*mock.Call
}

// DisableUnitFilesContext is a helper method to define mock.On call
//   - ctx context.Context
//   - files []string
//   - runtime bool
func (_e *MockConnector_Expecter) DisableUnitFilesContext(ctx interface{}, files interface{}, runtime interface{}) *MockConnector_DisableUnitFilesContext_Call {
	return &MockConnector_DisableUnitFilesContext_Call{Call: _e.mock.On("DisableUnitFilesContext", ctx, files, runtime)}
}

func (_c *MockConnector_DisableUnitFilesContext_Call) Run(run func(ctx context.Context, files []string, runtime bool)) *MockConnector_DisableUnitFilesContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(bool))
	})
	return _c
}

func (_c *MockConnector_DisableUnitFilesContext_Call) Return(_a0 []v22dbus.DisableUnitFileChange, _a1 error) *MockConnector_DisableUnitFilesContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnector_DisableUnitFilesContext_Call) RunAndReturn(run func(context.Context, []string, bool) ([]v22dbus.DisableUnitFileChange, error)) *MockConnector_DisableUnitFilesContext_Call {
	_c.Call.Return(run)
	return _c
}

// EnableUnitFilesContext provides a mock function with given fields: ctx, files, runtime, force
func (_m *MockConnector) EnableUnitFilesContext(ctx context.Context, files []string, runtime bool, force bool) (bool, []v22dbus.EnableUnitFileChange, error) {
	ret := _m.Called(ctx, files, runtime, force)

	if len(ret) == 0 {
		panic("no return value specified for EnableUnitFilesContext")
	}

	var r0 bool
	var r1 []v22dbus.EnableUnitFileChange
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, bool, bool) (bool, []v22dbus.EnableUnitFileChange, error)); ok {
		return rf(ctx, files, runtime, force)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, bool, bool) bool); ok {
		r0 = rf(ctx, files, runtime, force)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, bool, bool) []v22dbus.EnableUnitFileChange); ok {
		r1 = rf(ctx, files, runtime, force)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]v22dbus.EnableUnitFileChange)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, []string, bool, bool) error); ok {
		r2 = rf(ctx, files, runtime, force)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockConnector_EnableUnitFilesContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableUnitFilesContext'
type MockConnector_EnableUnitFilesContext_Call struct {
	*mock.Call
}

// EnableUnitFilesContext is a helper method to define mock.On call
//   - ctx context.Context
//   - files []string
//   - runtime bool
//   - force bool
func (_e *MockConnector_Expecter) EnableUnitFilesContext(ctx interface{}, files interface{}, runtime interface{}, force interface{}) *MockConnector_EnableUnitFilesContext_Call {
	return &MockConnector_EnableUnitFilesContext_Call{Call: _e.mock.On("EnableUnitFilesContext", ctx, files, runtime, force)}
}

func (_c *MockConnector_EnableUnitFilesContext_Call) Run(run func(ctx context.Context, files []string, runtime bool, force bool)) *MockConnector_EnableUnitFilesContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(bool), args[3].(bool))
	})
	return _c
}

func (_c *MockConnector_EnableUnitFilesContext_Call) Return(_a0 bool, _a1 []v22dbus.EnableUnitFileChange, _a2 error) *MockConnector_EnableUnitFilesContext_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockConnector_EnableUnitFilesContext_Call) RunAndReturn(run func(context.Context, []string, bool, bool) (bool, []v22dbus.EnableUnitFileChange, error)) *MockConnector_EnableUnitFilesContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnitPropertiesContext provides a mock function with given fields: ctx, unit
func (_m *MockConnector) GetUnitPropertiesContext(ctx context.Context, unit string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, unit)

	if len(ret) == 0 {
		panic("no return value specified for GetUnitPropertiesContext")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]interface{}, error)); ok {
		return rf(ctx, unit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]interface{}); ok {
		r0 = rf(ctx, unit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, unit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnector_GetUnitPropertiesContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnitPropertiesContext'
type MockConnector_GetUnitPropertiesContext_Call struct {
	*mock.Call
}

// GetUnitPropertiesContext is a helper method to define mock.On call
//   - ctx context.Context
//   - unit string
func (_e *MockConnector_Expecter) GetUnitPropertiesContext(ctx interface{}, unit interface{}) *MockConnector_GetUnitPropertiesContext_Call {
	return &MockConnector_GetUnitPropertiesContext_Call{Call: _e.mock.On("GetUnitPropertiesContext", ctx, unit)}
}

func (_c *MockConnector_GetUnitPropertiesContext_Call) Run(run func(ctx context.Context, unit string)) *MockConnector_GetUnitPropertiesContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConnector_GetUnitPropertiesContext_Call) Return(_a0 map[string]interface{}, _a1 error) *MockConnector_GetUnitPropertiesContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnector_GetUnitPropertiesContext_Call) RunAndReturn(run func(context.Context, string) (map[string]interface{}, error)) *MockConnector_GetUnitPropertiesContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnitPropertyContext provides a mock function with given fields: ctx, unit, propertyName
func (_m *MockConnector) GetUnitPropertyContext(ctx context.Context, unit string, propertyName string) (*v22dbus.Property, error) {
	ret := _m.Called(ctx, unit, propertyName)

	if len(ret) == 0 {
		panic("no return value specified for GetUnitPropertyContext")
	}

	var r0 *v22dbus.Property
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v22dbus.Property, error)); ok {
		return rf(ctx, unit, propertyName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v22dbus.Property); ok {
		r0 = rf(ctx, unit, propertyName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v22dbus.Property)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, unit, propertyName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnector_GetUnitPropertyContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnitPropertyContext'
type MockConnector_GetUnitPropertyContext_Call struct {
	*mock.Call
}

// GetUnitPropertyContext is a helper method to define mock.On call
//   - ctx context.Context
//   - unit string
//   - propertyName string
func (_e *MockConnector_Expecter) GetUnitPropertyContext(ctx interface{}, unit interface{}, propertyName interface{}) *MockConnector_GetUnitPropertyContext_Call {
	return &MockConnector_GetUnitPropertyContext_Call{Call: _e.mock.On("GetUnitPropertyContext", ctx, unit, propertyName)}
}

func (_c *MockConnector_GetUnitPropertyContext_Call) Run(run func(ctx context.Context, unit string, propertyName string)) *MockConnector_GetUnitPropertyContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockConnector_GetUnitPropertyContext_Call) Return(_a0 *v22dbus.Property, _a1 error) *MockConnector_GetUnitPropertyContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnector_GetUnitPropertyContext_Call) RunAndReturn(run func(context.Context, string, string) (*v22dbus.Property, error)) *MockConnector_GetUnitPropertyContext_Call {
	_c.Call.Return(run)
	return _c
}

// ListJobsContext provides a mock function with given fields: ctx
func (_m *MockConnector) ListJobsContext(ctx context.Context) ([]v22dbus.JobStatus, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListJobsContext")
	}

	var r0 []v22dbus.JobStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]v22dbus.JobStatus, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []v22dbus.JobStatus); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v22dbus.JobStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnector_ListJobsContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJobsContext'
type MockConnector_ListJobsContext_Call struct {
	*mock.Call
}

// ListJobsContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConnector_Expecter) ListJobsContext(ctx interface{}) *MockConnector_ListJobsContext_Call {
	return &MockConnector_ListJobsContext_Call{Call: _e.mock.On("ListJobsContext", ctx)}
}

func (_c *MockConnector_ListJobsContext_Call) Run(run func(ctx context.Context)) *MockConnector_ListJobsContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConnector_ListJobsContext_Call) Return(_a0 []v22dbus.JobStatus, _a1 error) *MockConnector_ListJobsContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnector_ListJobsContext_Call) RunAndReturn(run func(context.Context) ([]v22dbus.JobStatus, error)) *MockConnector_ListJobsContext_Call {
	_c.Call.Return(run)
	return _c
}

// ListUnitsByNamesContext provides a mock function with given fields: ctx, units
func (_m *MockConnector) ListUnitsByNamesContext(ctx context.Context, units []string) ([]v22dbus.UnitStatus, error) {
	ret := _m.Called(ctx, units)

	if len(ret) == 0 {
		panic("no return value specified for ListUnitsByNamesContext")
	}

	var r0 []v22dbus.UnitStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]v22dbus.UnitStatus, error)); ok {
		return rf(ctx, units)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []v22dbus.UnitStatus); ok {
		r0 = rf(ctx, units)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v22dbus.UnitStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, units)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnector_ListUnitsByNamesContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUnitsByNamesContext'
type MockConnector_ListUnitsByNamesContext_Call struct {
	*mock.Call
}

// ListUnitsByNamesContext is a helper method to define mock.On call
//   - ctx context.Context
//   - units []string
func (_e *MockConnector_Expecter) ListUnitsByNamesContext(ctx interface{}, units interface{}) *MockConnector_ListUnitsByNamesContext_Call {
	return &MockConnector_ListUnitsByNamesContext_Call{Call: _e.mock.On("ListUnitsByNamesContext", ctx, units)}
}

func (_c *MockConnector_ListUnitsByNamesContext_Call) Run(run func(ctx context.Context, units []string)) *MockConnector_ListUnitsByNamesContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockConnector_ListUnitsByNamesContext_Call) Return(_a0 []v22dbus.UnitStatus, _a1 error) *MockConnector_ListUnitsByNamesContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnector_ListUnitsByNamesContext_Call) RunAndReturn(run func(context.Context, []string) ([]v22dbus.UnitStatus, error)) *MockConnector_ListUnitsByNamesContext_Call {
	_c.Call.Return(run)
	return _c
}

// ListUnitsContext provides a mock function with given fields: ctx
func (_m *MockConnector) ListUnitsContext(ctx context.Context) ([]v22dbus.UnitStatus, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUnitsContext")
	}

	var r0 []v22dbus.UnitStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]v22dbus.UnitStatus, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []v22dbus.UnitStatus); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v22dbus.UnitStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnector_ListUnitsContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUnitsContext'
type MockConnector_ListUnitsContext_Call struct {
	*mock.Call
}

// ListUnitsContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConnector_Expecter) ListUnitsContext(ctx interface{}) *MockConnector_ListUnitsContext_Call {
	return &MockConnector_ListUnitsContext_Call{Call: _e.mock.On("ListUnitsContext", ctx)}
}

func (_c *MockConnector_ListUnitsContext_Call) Run(run func(ctx context.Context)) *MockConnector_ListUnitsContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConnector_ListUnitsContext_Call) Return(_a0 []v22dbus.UnitStatus, _a1 error) *MockConnector_ListUnitsContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnector_ListUnitsContext_Call) RunAndReturn(run func(context.Context) ([]v22dbus.UnitStatus, error)) *MockConnector_ListUnitsContext_Call {
	_c.Call.Return(run)
	return _c
}

// ReloadContext provides a mock function with given fields: ctx
func (_m *MockConnector) ReloadContext(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReloadContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnector_ReloadContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReloadContext'
type MockConnector_ReloadContext_Call struct {
	*mock.Call
}

// ReloadContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConnector_Expecter) ReloadContext(ctx interface{}) *MockConnector_ReloadContext_Call {
	return &MockConnector_ReloadContext_Call{Call: _e.mock.On("ReloadContext", ctx)}
}

func (_c *MockConnector_ReloadContext_Call) Run(run func(ctx context.Context)) *MockConnector_ReloadContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConnector_ReloadContext_Call) Return(_a0 error) *MockConnector_ReloadContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnector_ReloadContext_Call) RunAndReturn(run func(context.Context) error) *MockConnector_ReloadContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnector creates a new instance of MockConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnector {
	mock := &MockConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
