// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	dbus "github.com/coreos/go-systemd/v22/dbus"

	mock "github.com/stretchr/testify/mock"
)

// DbusConnector is an autogenerated mock type for the DbusConnector type
type DbusConnector struct {
	mock.Mock
}

// ListUnitsByNamesContext provides a mock function with given fields: ctx, units
func (_m *DbusConnector) ListUnitsByNamesContext(ctx context.Context, units []string) ([]dbus.UnitStatus, error) {
	ret := _m.Called(ctx, units)

	var r0 []dbus.UnitStatus
	if rf, ok := ret.Get(0).(func(context.Context, []string) []dbus.UnitStatus); ok {
		r0 = rf(ctx, units)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbus.UnitStatus)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, units)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
