// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GroupSearcher is an autogenerated mock type for the GroupSearcher type
type GroupSearcher struct {
	mock.Mock
}

// GetGroupByID provides a mock function with given fields: groupID
func (_m *GroupSearcher) GetGroupByID(groupID string) (string, error) {
	ret := _m.Called(groupID)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(groupID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(groupID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGroupSearcher creates a new instance of GroupSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupSearcher {
	mock := &GroupSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
