// Code generated by mockery v2.32.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HostnameResolver is an autogenerated mock type for the HostnameResolver type
type HostnameResolver struct {
	mock.Mock
}

// LookupHost provides a mock function with given fields: host
func (_m *HostnameResolver) LookupHost(host string) ([]string, error) {
	ret := _m.Called(host)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(host)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(host)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(host)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHostnameResolver creates a new instance of HostnameResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHostnameResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *HostnameResolver {
	mock := &HostnameResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
