// Code generated by mockery v2.32.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockHostnameResolver is an autogenerated mock type for the HostnameResolver type
type MockHostnameResolver struct {
	mock.Mock
}

type MockHostnameResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHostnameResolver) EXPECT() *MockHostnameResolver_Expecter {
	return &MockHostnameResolver_Expecter{mock: &_m.Mock}
}

// LookupHost provides a mock function with given fields: host
func (_m *MockHostnameResolver) LookupHost(host string) ([]string, error) {
	ret := _m.Called(host)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(host)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(host)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(host)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHostnameResolver_LookupHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupHost'
type MockHostnameResolver_LookupHost_Call struct {
	*mock.Call
}

// LookupHost is a helper method to define mock.On call
//   - host string
func (_e *MockHostnameResolver_Expecter) LookupHost(host interface{}) *MockHostnameResolver_LookupHost_Call {
	return &MockHostnameResolver_LookupHost_Call{Call: _e.mock.On("LookupHost", host)}
}

func (_c *MockHostnameResolver_LookupHost_Call) Run(run func(host string)) *MockHostnameResolver_LookupHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHostnameResolver_LookupHost_Call) Return(_a0 []string, _a1 error) *MockHostnameResolver_LookupHost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHostnameResolver_LookupHost_Call) RunAndReturn(run func(string) ([]string, error)) *MockHostnameResolver_LookupHost_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHostnameResolver creates a new instance of MockHostnameResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHostnameResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHostnameResolver {
	mock := &MockHostnameResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
