// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Adapter is an autogenerated mock type for the Adapter type
type Adapter struct {
	mock.Mock
}

// Listen provides a mock function with given fields: agentID, handle
func (_m *Adapter) Listen(agentID string, handle func(string, []byte) error) error {
	ret := _m.Called(agentID, handle)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(string, []byte) error) error); ok {
		r0 = rf(agentID, handle)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Publish provides a mock function with given fields: facts, eventType
func (_m *Adapter) Publish(facts []byte, eventType string) error {
	ret := _m.Called(facts, eventType)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, string) error); ok {
		r0 = rf(facts, eventType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Unsubscribe provides a mock function with given fields:
func (_m *Adapter) Unsubscribe() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
