// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	sapcontrolapi "github.com/trento-project/agent/internal/core/sapsystem/sapcontrolapi"
)

// WebServiceConnector is an autogenerated mock type for the WebServiceConnector type
type WebServiceConnector struct {
	mock.Mock
}

// New provides a mock function with given fields: instanceNumber
func (_m *WebServiceConnector) New(instanceNumber string) sapcontrolapi.WebService {
	ret := _m.Called(instanceNumber)

	var r0 sapcontrolapi.WebService
	if rf, ok := ret.Get(0).(func(string) sapcontrolapi.WebService); ok {
		r0 = rf(instanceNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sapcontrolapi.WebService)
		}
	}

	return r0
}

type NewWebServiceConnectorT interface {
	mock.TestingT
	Cleanup(func())
}

// NewWebServiceConnector creates a new instance of WebServiceConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWebServiceConnector(t NewWebServiceConnectorT) *WebServiceConnector {
	mock := &WebServiceConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
