// Code generated by mockery v2.32.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	sapcontrolapi "github.com/trento-project/agent/internal/core/sapsystem/sapcontrolapi"
)

// WebService is an autogenerated mock type for the WebService type
type WebService struct {
	mock.Mock
}

// GetInstanceProperties provides a mock function with given fields: ctx
func (_m *WebService) GetInstanceProperties(ctx context.Context) (*sapcontrolapi.GetInstancePropertiesResponse, error) {
	ret := _m.Called(ctx)

	var r0 *sapcontrolapi.GetInstancePropertiesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*sapcontrolapi.GetInstancePropertiesResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *sapcontrolapi.GetInstancePropertiesResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sapcontrolapi.GetInstancePropertiesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProcessList provides a mock function with given fields: ctx
func (_m *WebService) GetProcessList(ctx context.Context) (*sapcontrolapi.GetProcessListResponse, error) {
	ret := _m.Called(ctx)

	var r0 *sapcontrolapi.GetProcessListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*sapcontrolapi.GetProcessListResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *sapcontrolapi.GetProcessListResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sapcontrolapi.GetProcessListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSystemInstanceList provides a mock function with given fields: ctx
func (_m *WebService) GetSystemInstanceList(ctx context.Context) (*sapcontrolapi.GetSystemInstanceListResponse, error) {
	ret := _m.Called(ctx)

	var r0 *sapcontrolapi.GetSystemInstanceListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*sapcontrolapi.GetSystemInstanceListResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *sapcontrolapi.GetSystemInstanceListResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sapcontrolapi.GetSystemInstanceListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVersionInfo provides a mock function with given fields: ctx
func (_m *WebService) GetVersionInfo(ctx context.Context) (*sapcontrolapi.GetVersionInfoResponse, error) {
	ret := _m.Called(ctx)

	var r0 *sapcontrolapi.GetVersionInfoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*sapcontrolapi.GetVersionInfoResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *sapcontrolapi.GetVersionInfoResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sapcontrolapi.GetVersionInfoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HACheckConfig provides a mock function with given fields: ctx
func (_m *WebService) HACheckConfig(ctx context.Context) (*sapcontrolapi.HACheckConfigResponse, error) {
	ret := _m.Called(ctx)

	var r0 *sapcontrolapi.HACheckConfigResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*sapcontrolapi.HACheckConfigResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *sapcontrolapi.HACheckConfigResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sapcontrolapi.HACheckConfigResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HAGetFailoverConfig provides a mock function with given fields: ctx
func (_m *WebService) HAGetFailoverConfig(ctx context.Context) (*sapcontrolapi.HAGetFailoverConfigResponse, error) {
	ret := _m.Called(ctx)

	var r0 *sapcontrolapi.HAGetFailoverConfigResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*sapcontrolapi.HAGetFailoverConfigResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *sapcontrolapi.HAGetFailoverConfigResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sapcontrolapi.HAGetFailoverConfigResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWebService creates a new instance of WebService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebService {
	mock := &WebService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
