// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCmdClient is an autogenerated mock type for the CmdClient type
type MockCmdClient struct {
	mock.Mock
}

type MockCmdClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCmdClient) EXPECT() *MockCmdClient_Expecter {
	return &MockCmdClient_Expecter{mock: &_m.Mock}
}

// GetState provides a mock function with given fields: ctx
func (_m *MockCmdClient) GetState(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCmdClient_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type MockCmdClient_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCmdClient_Expecter) GetState(ctx interface{}) *MockCmdClient_GetState_Call {
	return &MockCmdClient_GetState_Call{Call: _e.mock.On("GetState", ctx)}
}

func (_c *MockCmdClient_GetState_Call) Run(run func(ctx context.Context)) *MockCmdClient_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCmdClient_GetState_Call) Return(_a0 string, _a1 error) *MockCmdClient_GetState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCmdClient_GetState_Call) RunAndReturn(run func(context.Context) (string, error)) *MockCmdClient_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// IsHostOnline provides a mock function with given fields: ctx
func (_m *MockCmdClient) IsHostOnline(ctx context.Context) bool {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsHostOnline")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCmdClient_IsHostOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsHostOnline'
type MockCmdClient_IsHostOnline_Call struct {
	*mock.Call
}

// IsHostOnline is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCmdClient_Expecter) IsHostOnline(ctx interface{}) *MockCmdClient_IsHostOnline_Call {
	return &MockCmdClient_IsHostOnline_Call{Call: _e.mock.On("IsHostOnline", ctx)}
}

func (_c *MockCmdClient_IsHostOnline_Call) Run(run func(ctx context.Context)) *MockCmdClient_IsHostOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCmdClient_IsHostOnline_Call) Return(_a0 bool) *MockCmdClient_IsHostOnline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCmdClient_IsHostOnline_Call) RunAndReturn(run func(context.Context) bool) *MockCmdClient_IsHostOnline_Call {
	_c.Call.Return(run)
	return _c
}

// IsIdle provides a mock function with given fields: ctx
func (_m *MockCmdClient) IsIdle(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsIdle")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCmdClient_IsIdle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsIdle'
type MockCmdClient_IsIdle_Call struct {
	*mock.Call
}

// IsIdle is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCmdClient_Expecter) IsIdle(ctx interface{}) *MockCmdClient_IsIdle_Call {
	return &MockCmdClient_IsIdle_Call{Call: _e.mock.On("IsIdle", ctx)}
}

func (_c *MockCmdClient_IsIdle_Call) Run(run func(ctx context.Context)) *MockCmdClient_IsIdle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCmdClient_IsIdle_Call) Return(_a0 bool, _a1 error) *MockCmdClient_IsIdle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCmdClient_IsIdle_Call) RunAndReturn(run func(context.Context) (bool, error)) *MockCmdClient_IsIdle_Call {
	_c.Call.Return(run)
	return _c
}

// ResourceRefresh provides a mock function with given fields: ctx, resourceID, nodeID
func (_m *MockCmdClient) ResourceRefresh(ctx context.Context, resourceID string, nodeID string) error {
	ret := _m.Called(ctx, resourceID, nodeID)

	if len(ret) == 0 {
		panic("no return value specified for ResourceRefresh")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, resourceID, nodeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCmdClient_ResourceRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourceRefresh'
type MockCmdClient_ResourceRefresh_Call struct {
	*mock.Call
}

// ResourceRefresh is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceID string
//   - nodeID string
func (_e *MockCmdClient_Expecter) ResourceRefresh(ctx interface{}, resourceID interface{}, nodeID interface{}) *MockCmdClient_ResourceRefresh_Call {
	return &MockCmdClient_ResourceRefresh_Call{Call: _e.mock.On("ResourceRefresh", ctx, resourceID, nodeID)}
}

func (_c *MockCmdClient_ResourceRefresh_Call) Run(run func(ctx context.Context, resourceID string, nodeID string)) *MockCmdClient_ResourceRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCmdClient_ResourceRefresh_Call) Return(_a0 error) *MockCmdClient_ResourceRefresh_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCmdClient_ResourceRefresh_Call) RunAndReturn(run func(context.Context, string, string) error) *MockCmdClient_ResourceRefresh_Call {
	_c.Call.Return(run)
	return _c
}

// StartCluster provides a mock function with given fields: ctx
func (_m *MockCmdClient) StartCluster(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCmdClient_StartCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartCluster'
type MockCmdClient_StartCluster_Call struct {
	*mock.Call
}

// StartCluster is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCmdClient_Expecter) StartCluster(ctx interface{}) *MockCmdClient_StartCluster_Call {
	return &MockCmdClient_StartCluster_Call{Call: _e.mock.On("StartCluster", ctx)}
}

func (_c *MockCmdClient_StartCluster_Call) Run(run func(ctx context.Context)) *MockCmdClient_StartCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCmdClient_StartCluster_Call) Return(_a0 error) *MockCmdClient_StartCluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCmdClient_StartCluster_Call) RunAndReturn(run func(context.Context) error) *MockCmdClient_StartCluster_Call {
	_c.Call.Return(run)
	return _c
}

// StopCluster provides a mock function with given fields: ctx
func (_m *MockCmdClient) StopCluster(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StopCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCmdClient_StopCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopCluster'
type MockCmdClient_StopCluster_Call struct {
	*mock.Call
}

// StopCluster is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCmdClient_Expecter) StopCluster(ctx interface{}) *MockCmdClient_StopCluster_Call {
	return &MockCmdClient_StopCluster_Call{Call: _e.mock.On("StopCluster", ctx)}
}

func (_c *MockCmdClient_StopCluster_Call) Run(run func(ctx context.Context)) *MockCmdClient_StopCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCmdClient_StopCluster_Call) Return(_a0 error) *MockCmdClient_StopCluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCmdClient_StopCluster_Call) RunAndReturn(run func(context.Context) error) *MockCmdClient_StopCluster_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCmdClient creates a new instance of MockCmdClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCmdClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCmdClient {
	mock := &MockCmdClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
