// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSaptune is an autogenerated mock type for the Saptune type
type MockSaptune struct {
	mock.Mock
}

type MockSaptune_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSaptune) EXPECT() *MockSaptune_Expecter {
	return &MockSaptune_Expecter{mock: &_m.Mock}
}

// ApplySolution provides a mock function with given fields: ctx, solution
func (_m *MockSaptune) ApplySolution(ctx context.Context, solution string) error {
	ret := _m.Called(ctx, solution)

	if len(ret) == 0 {
		panic("no return value specified for ApplySolution")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, solution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSaptune_ApplySolution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplySolution'
type MockSaptune_ApplySolution_Call struct {
	*mock.Call
}

// ApplySolution is a helper method to define mock.On call
//   - ctx context.Context
//   - solution string
func (_e *MockSaptune_Expecter) ApplySolution(ctx interface{}, solution interface{}) *MockSaptune_ApplySolution_Call {
	return &MockSaptune_ApplySolution_Call{Call: _e.mock.On("ApplySolution", ctx, solution)}
}

func (_c *MockSaptune_ApplySolution_Call) Run(run func(ctx context.Context, solution string)) *MockSaptune_ApplySolution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSaptune_ApplySolution_Call) Return(_a0 error) *MockSaptune_ApplySolution_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSaptune_ApplySolution_Call) RunAndReturn(run func(context.Context, string) error) *MockSaptune_ApplySolution_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeSolution provides a mock function with given fields: ctx, solution
func (_m *MockSaptune) ChangeSolution(ctx context.Context, solution string) error {
	ret := _m.Called(ctx, solution)

	if len(ret) == 0 {
		panic("no return value specified for ChangeSolution")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, solution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSaptune_ChangeSolution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeSolution'
type MockSaptune_ChangeSolution_Call struct {
	*mock.Call
}

// ChangeSolution is a helper method to define mock.On call
//   - ctx context.Context
//   - solution string
func (_e *MockSaptune_Expecter) ChangeSolution(ctx interface{}, solution interface{}) *MockSaptune_ChangeSolution_Call {
	return &MockSaptune_ChangeSolution_Call{Call: _e.mock.On("ChangeSolution", ctx, solution)}
}

func (_c *MockSaptune_ChangeSolution_Call) Run(run func(ctx context.Context, solution string)) *MockSaptune_ChangeSolution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSaptune_ChangeSolution_Call) Return(_a0 error) *MockSaptune_ChangeSolution_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSaptune_ChangeSolution_Call) RunAndReturn(run func(context.Context, string) error) *MockSaptune_ChangeSolution_Call {
	_c.Call.Return(run)
	return _c
}

// Check provides a mock function with given fields: ctx
func (_m *MockSaptune) Check(ctx context.Context) ([]byte, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSaptune_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockSaptune_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSaptune_Expecter) Check(ctx interface{}) *MockSaptune_Check_Call {
	return &MockSaptune_Check_Call{Call: _e.mock.On("Check", ctx)}
}

func (_c *MockSaptune_Check_Call) Run(run func(ctx context.Context)) *MockSaptune_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSaptune_Check_Call) Return(_a0 []byte, _a1 error) *MockSaptune_Check_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSaptune_Check_Call) RunAndReturn(run func(context.Context) ([]byte, error)) *MockSaptune_Check_Call {
	_c.Call.Return(run)
	return _c
}

// CheckVersionSupport provides a mock function with given fields: ctx
func (_m *MockSaptune) CheckVersionSupport(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckVersionSupport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSaptune_CheckVersionSupport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckVersionSupport'
type MockSaptune_CheckVersionSupport_Call struct {
	*mock.Call
}

// CheckVersionSupport is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSaptune_Expecter) CheckVersionSupport(ctx interface{}) *MockSaptune_CheckVersionSupport_Call {
	return &MockSaptune_CheckVersionSupport_Call{Call: _e.mock.On("CheckVersionSupport", ctx)}
}

func (_c *MockSaptune_CheckVersionSupport_Call) Run(run func(ctx context.Context)) *MockSaptune_CheckVersionSupport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSaptune_CheckVersionSupport_Call) Return(_a0 error) *MockSaptune_CheckVersionSupport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSaptune_CheckVersionSupport_Call) RunAndReturn(run func(context.Context) error) *MockSaptune_CheckVersionSupport_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppliedSolution provides a mock function with given fields: ctx
func (_m *MockSaptune) GetAppliedSolution(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAppliedSolution")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSaptune_GetAppliedSolution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppliedSolution'
type MockSaptune_GetAppliedSolution_Call struct {
	*mock.Call
}

// GetAppliedSolution is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSaptune_Expecter) GetAppliedSolution(ctx interface{}) *MockSaptune_GetAppliedSolution_Call {
	return &MockSaptune_GetAppliedSolution_Call{Call: _e.mock.On("GetAppliedSolution", ctx)}
}

func (_c *MockSaptune_GetAppliedSolution_Call) Run(run func(ctx context.Context)) *MockSaptune_GetAppliedSolution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSaptune_GetAppliedSolution_Call) Return(_a0 string, _a1 error) *MockSaptune_GetAppliedSolution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSaptune_GetAppliedSolution_Call) RunAndReturn(run func(context.Context) (string, error)) *MockSaptune_GetAppliedSolution_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with given fields: ctx, nonComplianceCheck
func (_m *MockSaptune) GetStatus(ctx context.Context, nonComplianceCheck bool) ([]byte, error) {
	ret := _m.Called(ctx, nonComplianceCheck)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) ([]byte, error)); ok {
		return rf(ctx, nonComplianceCheck)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool) []byte); ok {
		r0 = rf(ctx, nonComplianceCheck)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, nonComplianceCheck)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSaptune_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockSaptune_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - nonComplianceCheck bool
func (_e *MockSaptune_Expecter) GetStatus(ctx interface{}, nonComplianceCheck interface{}) *MockSaptune_GetStatus_Call {
	return &MockSaptune_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx, nonComplianceCheck)}
}

func (_c *MockSaptune_GetStatus_Call) Run(run func(ctx context.Context, nonComplianceCheck bool)) *MockSaptune_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool))
	})
	return _c
}

func (_c *MockSaptune_GetStatus_Call) Return(_a0 []byte, _a1 error) *MockSaptune_GetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSaptune_GetStatus_Call) RunAndReturn(run func(context.Context, bool) ([]byte, error)) *MockSaptune_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function with given fields: ctx
func (_m *MockSaptune) GetVersion(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSaptune_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockSaptune_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSaptune_Expecter) GetVersion(ctx interface{}) *MockSaptune_GetVersion_Call {
	return &MockSaptune_GetVersion_Call{Call: _e.mock.On("GetVersion", ctx)}
}

func (_c *MockSaptune_GetVersion_Call) Run(run func(ctx context.Context)) *MockSaptune_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSaptune_GetVersion_Call) Return(_a0 string, _a1 error) *MockSaptune_GetVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSaptune_GetVersion_Call) RunAndReturn(run func(context.Context) (string, error)) *MockSaptune_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// ListNote provides a mock function with given fields: ctx
func (_m *MockSaptune) ListNote(ctx context.Context) ([]byte, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListNote")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSaptune_ListNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNote'
type MockSaptune_ListNote_Call struct {
	*mock.Call
}

// ListNote is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSaptune_Expecter) ListNote(ctx interface{}) *MockSaptune_ListNote_Call {
	return &MockSaptune_ListNote_Call{Call: _e.mock.On("ListNote", ctx)}
}

func (_c *MockSaptune_ListNote_Call) Run(run func(ctx context.Context)) *MockSaptune_ListNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSaptune_ListNote_Call) Return(_a0 []byte, _a1 error) *MockSaptune_ListNote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSaptune_ListNote_Call) RunAndReturn(run func(context.Context) ([]byte, error)) *MockSaptune_ListNote_Call {
	_c.Call.Return(run)
	return _c
}

// ListSolution provides a mock function with given fields: ctx
func (_m *MockSaptune) ListSolution(ctx context.Context) ([]byte, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSolution")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSaptune_ListSolution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSolution'
type MockSaptune_ListSolution_Call struct {
	*mock.Call
}

// ListSolution is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSaptune_Expecter) ListSolution(ctx interface{}) *MockSaptune_ListSolution_Call {
	return &MockSaptune_ListSolution_Call{Call: _e.mock.On("ListSolution", ctx)}
}

func (_c *MockSaptune_ListSolution_Call) Run(run func(ctx context.Context)) *MockSaptune_ListSolution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSaptune_ListSolution_Call) Return(_a0 []byte, _a1 error) *MockSaptune_ListSolution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSaptune_ListSolution_Call) RunAndReturn(run func(context.Context) ([]byte, error)) *MockSaptune_ListSolution_Call {
	_c.Call.Return(run)
	return _c
}

// RevertSolution provides a mock function with given fields: ctx, solution
func (_m *MockSaptune) RevertSolution(ctx context.Context, solution string) error {
	ret := _m.Called(ctx, solution)

	if len(ret) == 0 {
		panic("no return value specified for RevertSolution")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, solution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSaptune_RevertSolution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevertSolution'
type MockSaptune_RevertSolution_Call struct {
	*mock.Call
}

// RevertSolution is a helper method to define mock.On call
//   - ctx context.Context
//   - solution string
func (_e *MockSaptune_Expecter) RevertSolution(ctx interface{}, solution interface{}) *MockSaptune_RevertSolution_Call {
	return &MockSaptune_RevertSolution_Call{Call: _e.mock.On("RevertSolution", ctx, solution)}
}

func (_c *MockSaptune_RevertSolution_Call) Run(run func(ctx context.Context, solution string)) *MockSaptune_RevertSolution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSaptune_RevertSolution_Call) Return(_a0 error) *MockSaptune_RevertSolution_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSaptune_RevertSolution_Call) RunAndReturn(run func(context.Context, string) error) *MockSaptune_RevertSolution_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyNote provides a mock function with given fields: ctx
func (_m *MockSaptune) VerifyNote(ctx context.Context) ([]byte, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for VerifyNote")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSaptune_VerifyNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyNote'
type MockSaptune_VerifyNote_Call struct {
	*mock.Call
}

// VerifyNote is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSaptune_Expecter) VerifyNote(ctx interface{}) *MockSaptune_VerifyNote_Call {
	return &MockSaptune_VerifyNote_Call{Call: _e.mock.On("VerifyNote", ctx)}
}

func (_c *MockSaptune_VerifyNote_Call) Run(run func(ctx context.Context)) *MockSaptune_VerifyNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSaptune_VerifyNote_Call) Return(_a0 []byte, _a1 error) *MockSaptune_VerifyNote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSaptune_VerifyNote_Call) RunAndReturn(run func(context.Context) ([]byte, error)) *MockSaptune_VerifyNote_Call {
	_c.Call.Return(run)
	return _c
}

// VerifySolution provides a mock function with given fields: ctx
func (_m *MockSaptune) VerifySolution(ctx context.Context) ([]byte, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for VerifySolution")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSaptune_VerifySolution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifySolution'
type MockSaptune_VerifySolution_Call struct {
	*mock.Call
}

// VerifySolution is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSaptune_Expecter) VerifySolution(ctx interface{}) *MockSaptune_VerifySolution_Call {
	return &MockSaptune_VerifySolution_Call{Call: _e.mock.On("VerifySolution", ctx)}
}

func (_c *MockSaptune_VerifySolution_Call) Run(run func(ctx context.Context)) *MockSaptune_VerifySolution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSaptune_VerifySolution_Call) Return(_a0 []byte, _a1 error) *MockSaptune_VerifySolution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSaptune_VerifySolution_Call) RunAndReturn(run func(context.Context) ([]byte, error)) *MockSaptune_VerifySolution_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSaptune creates a new instance of MockSaptune. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSaptune(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSaptune {
	mock := &MockSaptune{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
