// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDiscoverer is an autogenerated mock type for the Discoverer type
type MockDiscoverer[T interface{}] struct {
	mock.Mock
}

type MockDiscoverer_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockDiscoverer[T]) EXPECT() *MockDiscoverer_Expecter[T] {
	return &MockDiscoverer_Expecter[T]{mock: &_m.Mock}
}

// Discover provides a mock function with given fields: ctx
func (_m *MockDiscoverer[T]) Discover(ctx context.Context) (T, string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Discover")
	}

	var r0 T
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (T, string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) T); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) string); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockDiscoverer_Discover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discover'
type MockDiscoverer_Discover_Call[T interface{}] struct {
	*mock.Call
}

// Discover is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDiscoverer_Expecter[T]) Discover(ctx interface{}) *MockDiscoverer_Discover_Call[T] {
	return &MockDiscoverer_Discover_Call[T]{Call: _e.mock.On("Discover", ctx)}
}

func (_c *MockDiscoverer_Discover_Call[T]) Run(run func(ctx context.Context)) *MockDiscoverer_Discover_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDiscoverer_Discover_Call[T]) Return(_a0 T, _a1 string, _a2 error) *MockDiscoverer_Discover_Call[T] {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockDiscoverer_Discover_Call[T]) RunAndReturn(run func(context.Context) (T, string, error)) *MockDiscoverer_Discover_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockDiscoverer creates a new instance of MockDiscoverer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDiscoverer[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDiscoverer[T] {
	mock := &MockDiscoverer[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
